name: Aternos 7/24 Bot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Botu Başlat
        run: node index.js
        timeout-minutes: 350
